{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fastapi-ddd-template.fullname" . }}-config
  labels:
    {{- include "fastapi-ddd-template.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.config.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
