apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi-ddd-template-api.fullname" . }}
  labels:
    app: {{ include "fastapi-ddd-template-api.fullname" . }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "fastapi-ddd-template-api.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
