image:
  repository: placeholder
  tag: ""
  digest: ""

api:
  replicaCount: 1

db:
  persistence:
    enabled: false

dbBootstrap:
  enabled: true

config:
  enabled: true
  data:
    FASTAPI_DDD_TEMPLATE_ENV: "test"
    FASTAPI_DDD_TEMPLATE_DEBUG: "false"
    FASTAPI_DDD_TEMPLATE_LOG_DIR: "logs"
    SERVER_HOST: "127.0.0.1"
    SERVER_PORT: "8000"

    DB_ADMIN: "postgres"
    DB_PATH: "fastapi_ddd_template_stage_db"
    DB_HOST: "db"
    DB_DRIVER: "postgresql+asyncpg"
    DB_USER: "stage_db_user"
    DB_TABLE_SCHEMA: "fastapi_ddd_template"

    FASTAPI_DDD_TEMPLATE_BOOTSTRAP_FLAG: "true"
    FASTAPI_DDD_TEMPLATE_BOOTSTRAP_ADMIN: "admin"

secrets:
  existingName: "fastapi-ddd-template-secrets"
