apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-ddd-template-config
  namespace: staging
data:
  # ── FASTAPI_DDD_TEMPLATE application settings
  FASTAPI_DDD_TEMPLATE_ENV: "${STAGING_FASTAPI_DDD_TEMPLATE_ENV}"
  FASTAPI_DDD_TEMPLATE_DEBUG: "${STAGING_FASTAPI_DDD_TEMPLATE_DEBUG}"
  FASTAPI_DDD_TEMPLATE_LOG_DIR: "${STAGING_FASTAPI_DDD_TEMPLATE_LOG_DIR}"
  FASTAPI_DDD_TEMPLATE_JWT_ALGORITHM: "${STAGING_FASTAPI_DDD_TEMPLATE_JWT_ALGORITHM}"
  FASTAPI_DDD_TEMPLATE_JWT_TOKEN_EXPIRY_TIME: "${STAGING_FASTAPI_DDD_TEMPLATE_JWT_TOKEN_EXPIRY_TIME}"

  # ── FASTAPI_DDD_TEMPLATE entrypoint server settings
  SERVER_HOST: "${STAGING_SERVER_HOST}"
  SERVER_PORT: "${STAGING_SERVER_PORT}"

  # ── DB settings
  DB_ADMIN: "${STAGING_DB_ADMIN}"
  DB_PATH: "${STAGING_DB_PATH}"
  DB_HOST: "${STAGING_DB_HOST}" 
  DB_DRIVER: "${STAGING_DB_DRIVER}"
  DB_USER: "${STAGING_DB_USER}"
  DB_TABLE_SCHEMA: "${STAGING_DB_TABLE_SCHEMA}"

  # ── FASTAPI_DDD_TEMPLATE bootstrap settings
  FASTAPI_DDD_TEMPLATE_BOOTSTRAP_FLAG: "${STAGING_FASTAPI_DDD_TEMPLATE_BOOTSTRAP_FLAG}"
  FASTAPI_DDD_TEMPLATE_BOOTSTRAP_ADMIN: "${STAGING_FASTAPI_DDD_TEMPLATE_BOOTSTRAP_ADMIN}"
