image:
  repository: placeholder
  tag: ""
  digest: ""

config:
  enabled: true
  data:
    FASTAPI_DDD_TEMPLATE_ENV: "test"
    FASTAPI_DDD_TEMPLATE_DEBUG: "false"

    DB_ADMIN: "postgres"
    DB_USER: "stage_db_user"
    DB_PATH: "fastapi_ddd_template_stage_db"

    FASTAPI_DDD_TEMPLATE_BOOTSTRAP_FLAG: "true"
    FASTAPI_DDD_TEMPLATE_BOOTSTRAP_ADMIN: "admin"

api:
  replicaCount: 1

db:
  persistence:
    enabled: false

dbBootstrap:
  enabled: true
