image:
  repository: ""
  tag: ""
  digest: ""

config:
  enabled: true
  data:
    ENV: "test"
    DEBUG: "false"
    DB_USER: "ci_db_user"
    DB_PATH: "ci_db"

api:
  replicaCount: 1

db:
  persistence:
    enabled: false

dbBootstrap:
  enabled: true
