image:
  repository: ""
  tag: ""
  digest: ""

config:
  enabled: true
  data:
    ENV: "test"
    DEBUG: "false"
    DB_USER: "staging_db_user"
    DB_PATH: "staging_db"

api:
  replicas: 1
  service:
    type: LoadBalancer
    port: 80
  containerPort: 8000

db:
  persistence:
    enabled: true
    size: 1Gi
    storageClassName: local-path

image:
  # repository/digest set by workflow
  pullSecrets: []
