# app/domain/entities/user.py
from __future__ import annotations

from dataclasses import dataclass
from typing import Final, TypeVar

from app.domain.entities.base import Entity
from app.domain.exceptions.base import DomainError
from app.domain.value_objects import UserId, UserPasswordHash, UserRole, Username
from app.domain.services import IdGenerator

__all__: Final = ["User"]

@dataclass(eq=False, kw_only=True)
class User(Entity[UserId]):
    """
    Rich domain-model for a single system user.

    Only local invariants (those that need no repository look-ups) are enforced here.
    More global rules — e.g. “cannot disable last admin” — belong in a use-case.
    """

    username: Username
    password_hash: UserPasswordHash
    role: UserRole
    is_active: bool = True

    # ----------  Factory  --------------------------------------------------

    @classmethod
    def create(
        cls,
        username: Username,
        password_hash: UserPasswordHash,
        role: UserRole,
        id_gen: "IdGenerator",
    ) -> "User":
        """Create a new User with id generated by the supplied generator."""
        return cls(
            id=id_gen.new(),
            username=username,
            password_hash=password_hash,
            role=role
        )
    
    @classmethod
    def from_storage(
        cls,
        *,
        id: UserId,
        username: Username,
        password_hash: UserPasswordHash,
        role: UserRole,
        is_active: bool = True,
    ) -> "User":
        """
        Re-hydrate entity from persistence layer.
        Используется только репозиториями / дата-мапперами.
        """
        return cls(
            id=id,
            username=username,
            password_hash=password_hash,
            role=role,
            is_active=is_active,
        )
    # ----------  Behaviour  ------------------------------------------------

    # read-helpers ----------------------------------------------------------
    def is_admin(self) -> bool:
        """True if the user currently holds administrative privileges."""
        return self.role is UserRole.ADMIN

    # def check_password(self, hash_to_compare: UserPasswordHash) -> bool:
    #     """Compare hashes without leaking hashing details to callers."""
    #     return self.password_hash == hash_to_compare

    # state-changing methods ------------------------------------------------
    def change_username(self, new: Username) -> None:
        if new == self.username:
            raise DomainError("New username is identical to current")
        self.username = new  # type: ignore[misc]

    def change_password(self, new_hash: UserPasswordHash) -> None:
        if new_hash == self.password_hash:
            raise DomainError("New password hash matches the old one")
        self.password_hash = new_hash  # type: ignore[misc]

    def change_role(self, new: UserRole) -> None:
        if new == self.role:
            raise DomainError("Role is already set to the given value")
        self.role = new  # type: ignore[misc]
        if self.role == UserRole.ADMIN:
            self.is_active = True  # type: ignore[misc]

    def activate(self) -> None:
        if self.is_active:
            raise DomainError("User is already active")
        self.is_active = True  # type: ignore[misc]

    def deactivate(self) -> None:
        """
        Deactivate the account.

        Global invariant “last admin must stay active” is verified in the
        calling use-case; here мы проверяем только локальные ограничения.
        """
        if not self.is_active:
            raise DomainError("User is already inactive")
        self.is_active = False  # type: ignore[misc]
