# Generated by Django 5.2.11 on 2026-02-22 21:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=20, unique=True)),
                ("password_hash", models.BinaryField(max_length=60)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "admin"), ("user", "user")], max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "users",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("username",), name="uq_user_username"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("username__length__gte", 5)),
                        name="username_min_length",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSessionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(default=None, null=True)),
                (
                    "refresh_token_hash",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="django_orm.usermodel",
                    ),
                ),
            ],
            options={
                "db_table": "user_sessions",
            },
        ),
    ]
