"""init

Revision ID: eaf108d2c2ef
Revises: b3034a2ffc76
Create Date: 2025-12-06 00:07:43.836343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaf108d2c2ef'
down_revision: Union[str, Sequence[str], None] = 'b3034a2ffc76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('refresh_token_hash', sa.String(length=128), nullable=False))
    op.add_column('user_sessions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.drop_column('user_sessions', 'created_at')
    op.drop_column('user_sessions', 'refresh_token_hash')
    # ### end Alembic commands ###
