name: Release to staging

on:
  push:
    branches:
      - 'release/**'
  workflow_dispatch: {}

concurrency:
  group: release-staging-${{ github.repository }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  build_and_push:
    uses: ./.github/workflows/ci-push-to-ecr.yml
    secrets: inherit
    
  deploy_staging:
    needs: build_and_push
    uses: ./.github/workflows/cd-deploy-staging.yml
    secrets: inherit
    with:
      digest: ${{ needs.build_and_push.outputs.digest }}
      repo_path: ${{ needs.build_and_push.outputs.repo_path }}
      registry: ${{ needs.build_and_push.outputs.registry }}
