name: Release to CI runner

on:
  workflow_dispatch: {}

concurrency:
  group: release-ci-runner-${{ github.repository }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  build_and_push:
    uses: ./.github/workflows/ci-push-to-ghcr.yml
    secrets: inherit

  deploy_ci_runner:
    needs: build_and_push
    uses: ./.github/workflows/cd-deploy-ci-runner.yml
    secrets: inherit
    with:
      digest: ${{ needs.build_and_push.outputs.digest }}
      repo_path: ${{ needs.build_and_push.outputs.repo_path }}
      registry: ${{ needs.build_and_push.outputs.registry }}
